# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.9-alpine.3.14"
  armhf: "ghcr.io/home-assistant/armhf-base:3.9-alpine.3.14"
  
  
labels:
  org.opencontainers.image.title: "No-IP Host renewer"
  org.opencontainers.image.description: "No-IP Auto renewal of 30 day hosts"
  org.opencontainers.image.source: "https://github.com/habuild/"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
