# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: noip-renewer
version: "2022.3.0"
slug: noip-renewer
description: noip-renewer host auto renew
url: "https://github.com/habuild/hassio-addons/tree/master/noip-renewer"
arch:
  - armhf
  - aarch64
  
init: false
options:
  tag: "latest"
  email: "!secret email or username"
  password: "!secret noip_password"
schema:
  tag: "str"
  email: "str"
  password: "str"
image: "ghcr.io/habuild/{arch}-addon-noip-renewer"
